import React, { useState, useMemo, useEffect } from 'react';
import { HashRouter, Routes, Route, Link, useLocation, useNavigate } from 'react-router-dom';
import { Menu, ShoppingCart, X, Bike, Search, MapPin, Phone, Mail, Instagram, Facebook, Twitter, ArrowRight, ChevronRight, Check, Star, Lock, Plus, Edit, Trash, Save, Layout, Contact, Package, Wrench, FileText } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { PRODUCTS, BLOG_POSTS } from './constants';
import { Product, CartItem, Category, BlogPost } from './types';
import { Button } from './components/Button';
import { ProductCard } from './components/ProductCard';
import { Chatbot } from './components/Chatbot';

// --- Firebase Initialization ---
import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { 
  getFirestore, 
  doc, 
  collection, 
  onSnapshot, 
  setDoc, 
  updateDoc, 
  deleteDoc, 
  getDocFromServer,
  writeBatch
} from 'firebase/firestore';
import { signInWithPopup, GoogleAuthProvider, onAuthStateChanged, signOut } from 'firebase/auth';

// Use environment variables (Vercel) or local config (AI Studio)
// Note: firebase-applet-config.json is generated by AI Studio
import firebaseAppletConfig from './firebase-applet-config.json';

const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY || firebaseAppletConfig.apiKey,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || firebaseAppletConfig.authDomain,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || firebaseAppletConfig.projectId,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || firebaseAppletConfig.storageBucket,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || firebaseAppletConfig.messagingSenderId,
  appId: import.meta.env.VITE_FIREBASE_APP_ID || firebaseAppletConfig.appId,
  firestoreDatabaseId: import.meta.env.VITE_FIREBASE_DATABASE_ID || firebaseAppletConfig.firestoreDatabaseId,
};

const app = initializeApp(firebaseConfig);
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId || '(default)');
export const auth = getAuth();

// --- Error Handling ---
enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
  }
}

function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid,
      email: auth.currentUser?.email,
      emailVerified: auth.currentUser?.emailVerified,
      isAnonymous: auth.currentUser?.isAnonymous,
    },
    operationType,
    path
  }
  console.warn('Firestore Error: ', JSON.stringify(errInfo));
  // Not throwing here to prevent app crash on background sync errors
}

async function testConnection() {
  try {
    await getDocFromServer(doc(db, 'test', 'connection'));
    console.log("Firebase Connected");
  } catch (error) {
    if(error instanceof Error && error.message.includes('the client is offline')) {
      console.error("Please check your Firebase configuration.");
    }
  }
}
testConnection();

// --- Types for Content Management ---

interface FeaturedCategory {
  name: string;
  img: string;
  cat: Category;
}

interface Benefit {
  title: string;
  description: string;
  icon: 'Check' | 'Search' | 'ShoppingCart';
}

interface SiteContent {
  heroTitle: string;
  heroSubtitle: string;
  aboutTitle: string;
  aboutText: string;
  aboutImage: string;
  aboutSectionTitle: string;
  aboutSectionText: string;
  workshopTitle: string;
  workshopText: string;
  featuredCategories: FeaturedCategory[];
  benefits: Benefit[];
  heroVideo: string;
}

interface ContactInfo {
  address: string;
  phone: string;
  email: string;
  hoursWeek: string;
  hoursSat: string;
  locationTitle: string;
  hoursTitle: string;
  contactTitle: string;
}

// --- Helper Components for Layout ---

const Header = ({ 
  cartCount, 
  toggleCart, 
  toggleMobileMenu, 
  isMobileMenuOpen 
}: { 
  cartCount: number, 
  toggleCart: () => void,
  toggleMobileMenu: () => void,
  isMobileMenuOpen: boolean
}) => {
  const location = useLocation();
  
  const getLinkClass = (path: string) => {
    const isActive = location.pathname === path;
    return isActive 
      ? "text-orange-600 font-bold transition" 
      : "text-slate-600 hover:text-orange-600 font-medium transition";
  };

  const getMobileLinkClass = (path: string) => {
    const isActive = location.pathname === path;
    return isActive
      ? "block text-orange-600 font-bold bg-orange-50 px-3 py-2 rounded-md"
      : "block text-slate-600 hover:text-orange-600 font-medium px-3 py-2 hover:bg-slate-50 rounded-md";
  };

  return (
    <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-slate-100 shadow-sm transition-all duration-300">
      <div className="container mx-auto px-4">
        <div className="flex items-center justify-between h-20">
          {/* Logo */}
          <Link to="/" className="flex items-center space-x-2 text-2xl font-black text-slate-900 tracking-tighter group">
            <div className="bg-orange-600 p-1.5 rounded-lg group-hover:rotate-12 transition-transform duration-300">
              <Bike className="text-white h-6 w-6" />
            </div>
            <span>Jorge<span className="text-orange-600">Motos</span></span>
          </Link>

          {/* Desktop Nav */}
          <nav className="hidden md:flex items-center space-x-8">
            <Link to="/" className={getLinkClass("/")}>Inicio</Link>
            <Link to="/shop" className={getLinkClass("/shop")}>Tienda</Link>
            <Link to="/about" className={getLinkClass("/about")}>Quiénes Somos</Link>
            <Link to="/blog" className={getLinkClass("/blog")}>Blog</Link>
            <Link to="/contact" className={getLinkClass("/contact")}>Contacto</Link>
          </nav>

          {/* Actions */}
          <div className="flex items-center space-x-4">
            <button onClick={toggleCart} className="relative p-2 text-slate-600 hover:text-orange-600 transition">
              <ShoppingCart size={24} />
              {cartCount > 0 && (
                <span className="absolute top-0 right-0 bg-orange-600 text-white text-xs font-bold w-5 h-5 rounded-full flex items-center justify-center">
                  {cartCount}
                </span>
              )}
            </button>
            <button className="md:hidden p-2 text-slate-600" onClick={toggleMobileMenu}>
              {isMobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
            </button>
          </div>
        </div>
      </div>
      
      {/* Mobile Menu */}
      {isMobileMenuOpen && (
        <div className="md:hidden bg-white border-t border-slate-100 py-4 px-4 space-y-2 shadow-lg">
          <Link to="/" className={getMobileLinkClass("/")} onClick={toggleMobileMenu}>Inicio</Link>
          <Link to="/shop" className={getMobileLinkClass("/shop")} onClick={toggleMobileMenu}>Tienda</Link>
          <Link to="/about" className={getMobileLinkClass("/about")} onClick={toggleMobileMenu}>Quiénes Somos</Link>
          <Link to="/blog" className={getMobileLinkClass("/blog")} onClick={toggleMobileMenu}>Blog</Link>
          <Link to="/contact" className={getMobileLinkClass("/contact")} onClick={toggleMobileMenu}>Contacto</Link>
          <div className="pt-2 border-t border-slate-100 mt-2">
            <Link to="/admin" className="block text-slate-500 font-medium flex items-center px-3 py-2" onClick={toggleMobileMenu}>
              <Lock size={16} className="mr-2" /> Admin
            </Link>
          </div>
        </div>
      )}
    </header>
  );
};

const Footer = ({ contactInfo }: { contactInfo: ContactInfo }) => (
  <footer className="bg-slate-900 text-slate-300 py-12">
    <div className="container mx-auto px-4 grid grid-cols-1 md:grid-cols-4 gap-8">
      <div>
        <div className="flex items-center space-x-2 text-xl font-bold text-white mb-4">
          <Bike className="text-orange-600" />
          <span>JorgeMotos</span>
        </div>
        <p className="text-sm leading-relaxed">
          Especialistas en ciclismo urbano y de montaña. Calidad, servicio y pasión sobre dos ruedas.
        </p>
      </div>
      <div>
        <h4 className="text-white font-semibold mb-4">Enlaces Rápidos</h4>
        <ul className="space-y-2 text-sm">
          <li><Link to="/shop?category=Bicicletas" className="hover:text-orange-500 transition">Bicicletas</Link></li>
          <li><Link to="/shop?category=Repuestos" className="hover:text-orange-500 transition">Repuestos</Link></li>
          <li><Link to="/about" className="hover:text-orange-500 transition">Nosotros</Link></li>
          <li><Link to="/contact" className="hover:text-orange-500 transition">Soporte</Link></li>
        </ul>
      </div>
      <div>
        <h4 className="text-white font-semibold mb-4">Contacto</h4>
        <ul className="space-y-2 text-sm">
          <li className="flex items-center"><MapPin size={16} className="mr-2 text-orange-500"/> {contactInfo.address}</li>
          <li className="flex items-center"><Phone size={16} className="mr-2 text-orange-500"/> {contactInfo.phone}</li>
          <li className="flex items-center"><Mail size={16} className="mr-2 text-orange-500"/> {contactInfo.email}</li>
        </ul>
      </div>
      <div>
        <h4 className="text-white font-semibold mb-4">Síguenos</h4>
        <div className="flex space-x-4">
          <a href="#" className="bg-slate-800 p-2 rounded-full hover:bg-orange-600 transition"><Facebook size={18}/></a>
          <a href="#" className="bg-slate-800 p-2 rounded-full hover:bg-orange-600 transition"><Instagram size={18}/></a>
          <a href="#" className="bg-slate-800 p-2 rounded-full hover:bg-orange-600 transition"><Twitter size={18}/></a>
        </div>
        <div className="mt-6">
          <Link to="/admin" className="text-xs text-slate-600 hover:text-orange-500 flex items-center">
            <Lock size={12} className="mr-1" /> Acceso Admin
          </Link>
        </div>
      </div>
    </div>
    <div className="border-t border-slate-800 mt-10 pt-6 text-center text-xs text-slate-500">
      &copy; 2024 JorgeMotos. Todos los derechos reservados.
    </div>
  </footer>
);

// --- Pages ---

const HomePage = ({ content }: { content: SiteContent }) => {
  return (
    <div>
      {/* Hero Section */}
      <section className="relative h-[650px] flex items-center bg-slate-900 overflow-hidden">
        <div className="absolute inset-0 z-0">
          <motion.video 
            initial={{ opacity: 0 }}
            animate={{ opacity: 0.45 }}
            transition={{ duration: 1.5 }}
            autoPlay 
            muted 
            loop 
            playsInline
            className="w-full h-full object-cover"
          >
            <source src={content.heroVideo} type="video/mp4" />
          </motion.video>
          <div className="absolute inset-0 bg-gradient-to-r from-slate-900 via-slate-900/40 to-transparent z-10" />
        </div>
        <div className="container mx-auto px-4 relative z-20 text-white">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            <h1 className="text-5xl md:text-7xl font-black mb-6 leading-tight whitespace-pre-line tracking-tighter">
              {content.heroTitle}
            </h1>
          </motion.div>
          
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className="text-lg md:text-xl text-slate-300 mb-8 max-w-2xl leading-relaxed"
          >
            {content.heroSubtitle}
          </motion.p>
          
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.6 }}
            className="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4"
          >
            <Link to="/shop">
              <Button size="lg" className="w-full sm:w-auto bg-orange-600 hover:bg-orange-700 shadow-xl shadow-orange-900/30 text-lg px-8 py-6">
                Ver Catálogo <ArrowRight className="ml-2" />
              </Button>
            </Link>
            <Link to="/about">
              <Button size="lg" variant="outline" className="w-full sm:w-auto text-white border-white/30 hover:border-white hover:bg-white/10 text-lg px-8 py-6 backdrop-blur-sm">
                Conócenos
              </Button>
            </Link>
          </motion.div>
        </div>
        
        {/* Decorative elements */}
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 0.3 }}
          transition={{ duration: 2, delay: 1 }}
          className="absolute bottom-0 right-0 p-12 hidden lg:block"
        >
          <div className="w-64 h-64 border-4 border-white/5 rounded-full -mr-32 -mb-32" />
          <div className="w-96 h-96 border-4 border-white/5 rounded-full -mr-48 -mb-48" />
        </motion.div>
      </section>

      {/* Featured Categories */}
      <section className="py-20 bg-slate-50 overflow-hidden">
        <div className="container mx-auto px-4">
          <motion.h2 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-3xl font-bold text-center mb-12 text-slate-900"
          >
            Categorías Destacadas
          </motion.h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {content.featuredCategories.map((cat, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.1, duration: 0.5 }}
              >
                <Link to={`/shop?category=${cat.cat}`} className="group relative rounded-xl overflow-hidden h-64 shadow-lg block">
                  <img src={cat.img} alt={cat.name} className="w-full h-full object-cover transform group-hover:scale-110 transition duration-700" />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent flex items-end p-6">
                    <div>
                      <h3 className="text-2xl font-bold text-white mb-1 tracking-tight">{cat.name}</h3>
                      <span className="text-orange-400 font-medium flex items-center group-hover:translate-x-1 transition-transform">
                        Explorar <ChevronRight size={16} className="ml-1" />
                      </span>
                    </div>
                  </div>
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Why Choose Us */}
      <section className="py-20 bg-white border-y border-slate-100">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
             {content.benefits.map((benefit, idx) => (
              <div key={idx} className="p-6">
                <div className="w-16 h-16 bg-orange-100 text-orange-600 rounded-full flex items-center justify-center mx-auto mb-4">
                  {benefit.icon === 'Check' && <Check size={32} />}
                  {benefit.icon === 'Search' && <Search size={32} />}
                  {benefit.icon === 'ShoppingCart' && <ShoppingCart size={32} />}
                </div>
                <h3 className="text-xl font-bold mb-2">{benefit.title}</h3>
                <p className="text-slate-500">{benefit.description}</p>
              </div>
             ))}
          </div>
        </div>
      </section>
    </div>
  );
};

const ShopPage = ({ addToCart, products }: { addToCart: (p: Product) => void, products: Product[] }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [priceRange, setPriceRange] = useState<[number, number]>([0, 5000000]);
  const location = useLocation();

  React.useEffect(() => {
    const params = new URLSearchParams(location.search);
    const cat = params.get('category');
    if (cat) setSelectedCategory(cat);
  }, [location]);

  const filteredProducts = products.filter(product => {
    const matchesSearch = product.name.toLowerCase().includes(searchTerm.toLowerCase());
    
    let matchesCategory = false;
    if (selectedCategory === 'all') {
      matchesCategory = true;
    } else if (selectedCategory === 'Bicicletas') {
      matchesCategory = [Category.BIKES_MOUNTAIN, Category.BIKES_ROAD, Category.BIKES_URBAN].includes(product.category);
    } else if (selectedCategory === 'Repuestos') {
       matchesCategory = [Category.PARTS_BRAKES, Category.PARTS_DRIVETRAIN, Category.PARTS_WHEELS].includes(product.category);
    } else {
      matchesCategory = product.category === selectedCategory;
    }

    const matchesPrice = product.price >= priceRange[0] && product.price <= priceRange[1];
    return matchesSearch && matchesCategory && matchesPrice;
  });

  const [viewProduct, setViewProduct] = useState<Product | null>(null);

  if (viewProduct) {
    return (
      <div className="container mx-auto px-4 py-12">
        <button onClick={() => setViewProduct(null)} className="mb-6 text-slate-500 hover:text-orange-600 flex items-center">
          <ArrowRight className="transform rotate-180 mr-2" /> Volver a la tienda
        </button>
        <div className="bg-white rounded-xl shadow-lg overflow-hidden border border-slate-100">
          <div className="grid grid-cols-1 md:grid-cols-2">
            <div className="h-96 md:h-full bg-slate-100 relative">
              <img src={viewProduct.image} alt={viewProduct.name} className="w-full h-full object-cover" />
            </div>
            <div className="p-8 md:p-12">
              <div className="text-orange-600 font-bold mb-2">{viewProduct.category}</div>
              <h1 className="text-3xl font-extrabold text-slate-900 mb-4">{viewProduct.name}</h1>
              <div className="flex items-center mb-6">
                <div className="flex text-yellow-400 mr-2">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} size={20} className={i < Math.floor(viewProduct.rating) ? "fill-current" : "text-gray-300"} />
                  ))}
                </div>
                <span className="text-slate-500 text-sm">{viewProduct.reviews} reseñas verificadas</span>
              </div>
              <p className="text-slate-600 text-lg mb-8 leading-relaxed">
                {viewProduct.description}
              </p>
              
              <div className="mb-8">
                <h3 className="font-bold text-slate-900 mb-3">Especificaciones Técnicas</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  {Object.entries(viewProduct.specs).map(([key, val]) => (
                    <div key={key} className="flex flex-col">
                      <span className="text-slate-400">{key}</span>
                      <span className="font-medium text-slate-700">{val}</span>
                    </div>
                  ))}
                </div>
              </div>

              {viewProduct.category.startsWith('Bicicletas') && ( 
                 <div className="mb-8 p-4 bg-slate-50 rounded-lg text-sm text-slate-600">
                    <span className="font-bold block mb-1">📏 Guía de Tallas Recomendada:</span>
                    <ul className="list-disc list-inside">
                        <li>1.60m - 1.70m: Talla S</li>
                        <li>1.70m - 1.80m: Talla M</li>
                        <li>1.80m+: Talla L</li>
                    </ul>
                 </div>
              )}

              <div className="flex items-center justify-between pt-6 border-t border-slate-100">
                <span className="text-3xl font-bold text-slate-900">${viewProduct.price.toLocaleString()}</span>
                <Button size="lg" onClick={() => addToCart(viewProduct)}>Agregar al Carrito</Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="container mx-auto px-4 py-12">
      <div className="flex flex-col md:flex-row gap-8">
        {/* Sidebar Filters */}
        <aside className="w-full md:w-64 flex-shrink-0">
          <div className="bg-white p-6 rounded-lg shadow-sm border border-slate-200 sticky top-24">
            <h3 className="font-bold text-lg mb-4">Filtrar por</h3>
            
            <div className="mb-6">
              <label className="text-sm font-semibold text-slate-500 block mb-2">Categoría</label>
              <select 
                value={selectedCategory} 
                onChange={(e) => setSelectedCategory(e.target.value)}
                className="w-full border-slate-300 rounded-md shadow-sm focus:border-orange-500 focus:ring-orange-500"
              >
                <option value="all">Todas las Categorías</option>
                <option value="Bicicletas">🚲 Bicicletas (Todas)</option>
                <option value="Repuestos">⚙️ Repuestos (Todos)</option>
                <option disabled>──────────</option>
                {Object.values(Category).map(cat => (
                  <option key={cat} value={cat}>{cat}</option>
                ))}
              </select>
            </div>

            <div className="mb-6">
               <label className="text-sm font-semibold text-slate-500 block mb-2">Precio Máximo</label>
               <input 
                 type="range" 
                 min="0" 
                 max="5000000" 
                 step="100000"
                 value={priceRange[1]} 
                 onChange={(e) => setPriceRange([0, parseInt(e.target.value)])}
                 className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-orange-600"
               />
               <div className="text-right text-sm text-slate-700 mt-2">${priceRange[1].toLocaleString()}</div>
            </div>
          </div>
        </aside>

        {/* Product Grid */}
        <div className="flex-1">
          <div className="mb-6 flex items-center bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
            <Search className="text-slate-400 mr-3" />
            <input 
              type="text" 
              placeholder="Buscar bicicletas, repuestos..." 
              className="flex-1 outline-none text-slate-700"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>

          {filteredProducts.length === 0 ? (
             <div className="text-center py-20">
               <p className="text-slate-500 text-lg">No encontramos productos con esos criterios.</p>
             </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredProducts.map(product => (
                <ProductCard 
                  key={product.id} 
                  product={product} 
                  onAddToCart={addToCart} 
                  onClick={() => setViewProduct(product)}
                />
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// --- Admin Component ---

interface AdminProps {
  products: Product[];
  siteContent: SiteContent;
  contactInfo: ContactInfo;
  blogPosts: BlogPost[];
}

const AdminPage = ({ products, siteContent, contactInfo, blogPosts }: AdminProps) => {
  const [user, setUser] = useState(auth.currentUser);
  const [isAuthenticated, setIsAuthenticated] = useState(() => localStorage.getItem('jm_admin_auth') === 'true');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState<'products' | 'content' | 'contact' | 'blog'>('products');

  useEffect(() => {
    return onAuthStateChanged(auth, (u) => setUser(u));
  }, []);

  const ADMIN_KEY = "admin123"; // Clave de acceso
  const ADMIN_EMAIL = "sergio.polanco2018@gmail.com";

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (password === ADMIN_KEY) {
      setIsAuthenticated(true);
      localStorage.setItem('jm_admin_auth', 'true');
      setError('');
    } else {
      setError('Clave incorrecta. Inténtalo de nuevo.');
    }
  };

  const handleGoogleLogin = async () => {
    const provider = new GoogleAuthProvider();
    try {
      await signInWithPopup(auth, provider);
    } catch (e: any) {
      console.error(e);
      if (e.code === 'auth/unauthorized-domain') {
        setError('Error: Dominio no autorizado. Debes agregar "' + window.location.hostname + '" a la lista de dominios autorizados en la Consola de Firebase -> Authentication -> Settings.');
      } else {
        setError('Error al iniciar sesión con Google: ' + (e.message || 'Error desconocido'));
      }
    }
  };

  const handleLogout = async () => {
    await signOut(auth);
    setIsAuthenticated(false);
    localStorage.removeItem('jm_admin_auth');
  };

  const isFullyAuthorized = isAuthenticated && user?.email === ADMIN_EMAIL;

  if (!isFullyAuthorized) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center bg-slate-50 px-4">
        <div className="bg-white p-8 rounded-2xl shadow-xl border border-slate-200 w-full max-w-md">
          <div className="text-center mb-8">
            <div className="w-16 h-16 bg-orange-100 text-orange-600 rounded-full flex items-center justify-center mx-auto mb-4">
              <Lock size={32} />
            </div>
            <h1 className="text-2xl font-bold text-slate-900">Acceso Administrativo</h1>
            <p className="text-slate-500 mt-2">Ingresa la clave y verifica tu identidad para sincronizar cambios.</p>
          </div>
          
          {!isAuthenticated ? (
            <form onSubmit={handleLogin} className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Clave Secreta</label>
                <input 
                  type="password" 
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full border border-slate-300 rounded-lg p-3 focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none transition"
                  placeholder="••••••••"
                  required
                />
              </div>
              {error && <p className="text-red-500 text-sm font-medium">{error}</p>}
              <Button type="submit" className="w-full py-3 text-lg">Validar Clave</Button>
            </form>
          ) : (
            <div className="space-y-6">
              <div className="bg-green-50 text-green-700 p-3 rounded-lg text-sm font-medium text-center">
                ✅ Clave validada correctamente
              </div>
              <p className="text-slate-500 text-sm text-center">Ahora inicia sesión con Google para habilitar la edición en la nube.</p>
              <Button onClick={handleGoogleLogin} variant="outline" className="w-full flex items-center justify-center gap-2">
                <img src="https://www.google.com/favicon.ico" className="w-4 h-4" alt="Google" />
                Iniciar Sesión como {ADMIN_EMAIL}
              </Button>
              {error && <p className="text-red-500 text-sm font-medium">{error}</p>}
              <button onClick={() => setIsAuthenticated(false)} className="w-full text-slate-400 text-sm hover:underline">Cambiar Clave</button>
            </div>
          )}
          
          <div className="mt-8 pt-6 border-t border-slate-100 text-center">
            <Link to="/" className="text-slate-400 hover:text-slate-600 text-sm transition">
              &larr; Volver al sitio público
            </Link>
          </div>
        </div>
      </div>
    );
  }
  
  // Product Logic
  const [isEditing, setIsEditing] = useState(false);
  const [productForm, setProductForm] = useState<Partial<Product>>({
    name: '', price: 0, category: Category.BIKES_URBAN, image: 'https://picsum.photos/600/400', description: '', specs: {}, rating: 5, reviews: 0
  });

  const resetProductForm = () => {
    setProductForm({ name: '', price: 0, category: Category.BIKES_URBAN, image: 'https://picsum.photos/600/400', description: '', specs: {}, rating: 5, reviews: 0 });
    setIsEditing(false);
  };

  const handleProductEdit = (product: Product) => {
    setProductForm(product);
    setIsEditing(true);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleProductDelete = async (id: string) => {
    if (window.confirm('¿Eliminar producto?')) {
      try {
        await deleteDoc(doc(db, 'products', id));
      } catch (error) {
        handleFirestoreError(error, OperationType.DELETE, `products/${id}`);
      }
    }
  };

  const handleProductSave = async (e: React.FormEvent) => {
    e.preventDefault();
    const id = isEditing && productForm.id ? productForm.id : Date.now().toString();
    const finalProduct = { 
      ...productForm as Product, 
      id, 
      specs: productForm.specs || {},
      updatedAt: new Date().toISOString()
    };
    
    try {
      await setDoc(doc(db, 'products', id), finalProduct);
      resetProductForm();
      alert('Producto guardado.');
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, `products/${id}`);
    }
  };

  const handleProductChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setProductForm(prev => ({ ...prev, [name]: name === 'price' ? Number(value) : value }));
  };

  // Blog Logic
  const [isEditingBlog, setIsEditingBlog] = useState(false);
  const [blogForm, setBlogForm] = useState<Partial<BlogPost>>({
    title: '', excerpt: '', image: 'https://picsum.photos/800/400', date: new Date().toISOString().split('T')[0], category: 'General'
  });

  const resetBlogForm = () => {
    setBlogForm({ title: '', excerpt: '', image: 'https://picsum.photos/800/400', date: new Date().toISOString().split('T')[0], category: 'General' });
    setIsEditingBlog(false);
  };

  const handleBlogEdit = (post: BlogPost) => {
    setBlogForm(post);
    setIsEditingBlog(true);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleBlogDelete = async (id: string) => {
    if (window.confirm('¿Eliminar noticia?')) {
      try {
        await deleteDoc(doc(db, 'blogPosts', id));
      } catch (error) {
        handleFirestoreError(error, OperationType.DELETE, `blogPosts/${id}`);
      }
    }
  };

  const handleBlogSave = async (e: React.FormEvent) => {
    e.preventDefault();
    const id = isEditingBlog && blogForm.id ? blogForm.id : Date.now().toString();
    const finalPost = { ...blogForm as BlogPost, id };
    
    try {
      await setDoc(doc(db, 'blogPosts', id), finalPost);
      resetBlogForm();
      alert('Noticia guardada.');
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, `blogPosts/${id}`);
    }
  };

  const handleBlogChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setBlogForm(prev => ({ ...prev, [name]: value }));
  };


  // Content Logic
  const handleContentChange = async (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    const newContent = { ...siteContent, [name]: value };
    try {
      await setDoc(doc(db, 'config', 'siteContent'), newContent);
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, 'config/siteContent');
    }
  };

  const handleArrayContentChange = async (section: 'featuredCategories' | 'benefits', index: number, field: string, value: string) => {
    const newArray = [...siteContent[section]];
    (newArray[index] as any)[field] = value;
    const newContent = { ...siteContent, [section]: newArray };
    try {
      await setDoc(doc(db, 'config', 'siteContent'), newContent);
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, 'config/siteContent');
    }
  };

  // Contact Logic
  const handleContactChange = async (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    const newContact = { ...contactInfo, [name]: value };
    try {
      await setDoc(doc(db, 'config', 'contactInfo'), newContact);
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, 'config/contactInfo');
    }
  };

  const inputClass = "w-full border p-2 rounded bg-slate-50 focus:bg-white focus:ring-orange-500 focus:border-orange-500 transition-colors";

  return (
    <div className="container mx-auto px-4 py-12">
      <div className="flex items-center justify-between mb-8">
        <h1 className="text-3xl font-bold text-slate-900 flex items-center">
          <Lock className="mr-3 text-orange-600" /> Panel de Administración
        </h1>
        <button 
          onClick={handleLogout}
          className="bg-slate-100 text-slate-600 px-4 py-2 rounded-lg font-medium hover:bg-slate-200 transition"
        >
          Cerrar Sesión
        </button>
      </div>

      {/* Admin Tabs */}
      <div className="flex space-x-2 mb-8 border-b border-slate-200 overflow-x-auto">
        <button 
          onClick={() => setActiveTab('products')}
          className={`px-4 py-2 font-medium flex items-center whitespace-nowrap ${activeTab === 'products' ? 'text-orange-600 border-b-2 border-orange-600' : 'text-slate-500 hover:text-slate-800'}`}
        >
          <Package className="mr-2" size={18} /> Productos
        </button>
        <button 
          onClick={() => setActiveTab('content')}
          className={`px-4 py-2 font-medium flex items-center whitespace-nowrap ${activeTab === 'content' ? 'text-orange-600 border-b-2 border-orange-600' : 'text-slate-500 hover:text-slate-800'}`}
        >
          <Layout className="mr-2" size={18} /> Contenidos
        </button>
        <button 
          onClick={() => setActiveTab('contact')}
          className={`px-4 py-2 font-medium flex items-center whitespace-nowrap ${activeTab === 'contact' ? 'text-orange-600 border-b-2 border-orange-600' : 'text-slate-500 hover:text-slate-800'}`}
        >
          <Contact className="mr-2" size={18} /> Contacto
        </button>
        <button 
          onClick={() => setActiveTab('blog')}
          className={`px-4 py-2 font-medium flex items-center whitespace-nowrap ${activeTab === 'blog' ? 'text-orange-600 border-b-2 border-orange-600' : 'text-slate-500 hover:text-slate-800'}`}
        >
          <FileText className="mr-2" size={18} /> Blog
        </button>
      </div>

      {/* PRODUCTS TAB */}
      {activeTab === 'products' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="bg-white p-6 rounded-xl shadow-md border border-slate-200 h-fit lg:sticky lg:top-24">
            <h2 className="text-xl font-bold mb-6 flex items-center">
              {isEditing ? <Edit className="mr-2 text-blue-500" size={20}/> : <Plus className="mr-2 text-green-500" size={20}/>}
              {isEditing ? 'Editar Producto' : 'Agregar Nuevo Producto'}
            </h2>
            <form onSubmit={handleProductSave} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Nombre</label>
                <input type="text" name="name" required value={productForm.name} onChange={handleProductChange} className={inputClass} />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Precio ($)</label>
                  <input type="number" name="price" required min="0" value={productForm.price} onChange={handleProductChange} className={inputClass} />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Categoría</label>
                  <select name="category" value={productForm.category} onChange={handleProductChange} className={inputClass}>
                    {Object.values(Category).map(cat => <option key={cat} value={cat}>{cat}</option>)}
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Imagen URL</label>
                <input type="text" name="image" value={productForm.image} onChange={handleProductChange} className={inputClass} />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Descripción</label>
                <textarea name="description" rows={4} required value={productForm.description} onChange={handleProductChange} className={inputClass} />
              </div>
              <div className="flex space-x-3 pt-4">
                <Button type="submit" className="flex-1"><Save size={18} className="mr-2" /> Guardar</Button>
                {isEditing && <Button type="button" variant="outline" onClick={resetProductForm}>Cancelar</Button>}
              </div>
            </form>
          </div>

          <div className="lg:col-span-2 bg-white rounded-xl shadow-md border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left text-slate-500">
              <thead className="text-xs text-slate-700 uppercase bg-white border-b border-slate-200">
                <tr><th className="px-6 py-3">Producto</th><th className="px-6 py-3">Categoría</th><th className="px-6 py-3">Precio</th><th className="px-6 py-3 text-right">Acciones</th></tr>
              </thead>
              <tbody>
                {products.map(product => (
                  <tr key={product.id} className="bg-white border-b hover:bg-slate-50">
                    <td className="px-6 py-4 font-medium text-slate-900 flex items-center"><img src={product.image} className="w-8 h-8 rounded mr-3" />{product.name}</td>
                    <td className="px-6 py-4"><span className="bg-orange-100 text-orange-800 text-xs px-2 py-0.5 rounded">{product.category}</span></td>
                    <td className="px-6 py-4">${product.price.toLocaleString()}</td>
                    <td className="px-6 py-4 text-right space-x-2">
                      <button onClick={() => handleProductEdit(product)} className="text-blue-600"><Edit size={18} /></button>
                      <button onClick={() => handleProductDelete(product.id)} className="text-red-600"><Trash size={18} /></button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* BLOG TAB */}
      {activeTab === 'blog' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="bg-white p-6 rounded-xl shadow-md border border-slate-200 h-fit lg:sticky lg:top-24">
            <h2 className="text-xl font-bold mb-6 flex items-center">
              {isEditingBlog ? <Edit className="mr-2 text-blue-500" size={20}/> : <Plus className="mr-2 text-green-500" size={20}/>}
              {isEditingBlog ? 'Editar Noticia' : 'Nueva Noticia'}
            </h2>
            <form onSubmit={handleBlogSave} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Título</label>
                <input type="text" name="title" required value={blogForm.title} onChange={handleBlogChange} className={inputClass} />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Fecha</label>
                  <input type="date" name="date" required value={blogForm.date} onChange={handleBlogChange} className={inputClass} />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Categoría</label>
                  <input type="text" name="category" required value={blogForm.category} onChange={handleBlogChange} className={inputClass} />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Imagen URL</label>
                <input type="text" name="image" value={blogForm.image} onChange={handleBlogChange} className={inputClass} />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Extracto / Resumen</label>
                <textarea name="excerpt" rows={5} required value={blogForm.excerpt} onChange={handleBlogChange} className={inputClass} />
              </div>
              <div className="flex space-x-3 pt-4">
                <Button type="submit" className="flex-1"><Save size={18} className="mr-2" /> Guardar</Button>
                {isEditingBlog && <Button type="button" variant="outline" onClick={resetBlogForm}>Cancelar</Button>}
              </div>
            </form>
          </div>

          <div className="lg:col-span-2 bg-white rounded-xl shadow-md border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left text-slate-500">
              <thead className="text-xs text-slate-700 uppercase bg-white border-b border-slate-200">
                <tr><th className="px-6 py-3">Noticia</th><th className="px-6 py-3">Fecha</th><th className="px-6 py-3 text-right">Acciones</th></tr>
              </thead>
              <tbody>
                {blogPosts.map(post => (
                  <tr key={post.id} className="bg-white border-b hover:bg-slate-50">
                    <td className="px-6 py-4 font-medium text-slate-900">
                      <div className="flex items-center">
                        <img src={post.image} className="w-12 h-8 object-cover rounded mr-3" />
                        <div>
                          <div className="font-bold">{post.title}</div>
                          <span className="text-xs text-orange-600 bg-orange-50 px-2 rounded-full">{post.category}</span>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4">{post.date}</td>
                    <td className="px-6 py-4 text-right space-x-2">
                      <button onClick={() => handleBlogEdit(post)} className="text-blue-600"><Edit size={18} /></button>
                      <button onClick={() => handleBlogDelete(post.id)} className="text-red-600"><Trash size={18} /></button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* CONTENT TAB */}
      {activeTab === 'content' && (
        <div className="max-w-4xl mx-auto space-y-8">
          <div className="bg-white p-8 rounded-xl shadow-md border border-slate-200">
            <h2 className="text-xl font-bold mb-6 flex items-center italic">
              <Layout className="mr-2 text-orange-600" size={20} /> Textos Básicos
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-4">
                <h3 className="font-bold text-slate-900 border-b pb-2">Página de Inicio</h3>
                <div>
                  <label className="block text-sm font-bold text-slate-700 mb-1">Título Principal (Hero)</label>
                  <input type="text" name="heroTitle" value={siteContent.heroTitle} onChange={handleContentChange} className={inputClass} />
                </div>
                <div>
                  <label className="block text-sm font-bold text-slate-700 mb-1">URL Video de Portada (.mp4)</label>
                  <input type="text" name="heroVideo" value={siteContent.heroVideo} onChange={handleContentChange} className={inputClass} />
                </div>
                <div>
                  <label className="block text-sm font-bold text-slate-700 mb-1">Subtítulo (Hero)</label>
                  <textarea name="heroSubtitle" rows={2} value={siteContent.heroSubtitle} onChange={handleContentChange} className={inputClass} />
                </div>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold text-slate-900 border-b pb-2">Sección Taller</h3>
                <div>
                  <label className="block text-sm font-bold text-slate-700 mb-1">Título Taller</label>
                  <input type="text" name="workshopTitle" value={siteContent.workshopTitle} onChange={handleContentChange} className={inputClass} />
                </div>
                <div>
                  <label className="block text-sm font-bold text-slate-700 mb-1">Descripción Taller</label>
                  <textarea name="workshopText" rows={3} value={siteContent.workshopText} onChange={handleContentChange} className={inputClass} />
                </div>
              </div>
            </div>

            <div className="space-y-4 mt-8 pt-8 border-t">
              <h3 className="font-bold text-slate-900 border-b pb-2 text-center uppercase tracking-wider text-xs">Página Quiénes Somos</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-1">Título Grande</label>
                    <input type="text" name="aboutTitle" value={siteContent.aboutTitle} onChange={handleContentChange} className={inputClass} />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-1">Párrafo Introductorio</label>
                    <textarea name="aboutText" rows={4} value={siteContent.aboutText} onChange={handleContentChange} className={inputClass} />
                  </div>
                </div>
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-1">Título Sección Secundaria</label>
                    <input type="text" name="aboutSectionTitle" value={siteContent.aboutSectionTitle} onChange={handleContentChange} className={inputClass} />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-1">Texto Sección Secundaria</label>
                    <textarea name="aboutSectionText" rows={4} value={siteContent.aboutSectionText} onChange={handleContentChange} className={inputClass} />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Categorías Destacadas Editor */}
          <div className="bg-white p-8 rounded-xl shadow-md border border-slate-200">
            <h2 className="text-xl font-bold mb-6 flex items-center underline decoration-orange-500 decoration-2 underline-offset-4">
              🖼️ Categorías Destacadas (Inicio)
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {siteContent.featuredCategories.map((cat, idx) => (
                <div key={idx} className="p-4 border rounded-lg bg-slate-50 space-y-3">
                  <h4 className="font-bold text-sm text-slate-500">Categoría {idx + 1}</h4>
                  <div>
                    <label className="text-xs font-bold text-slate-400 block mb-1">Nombre</label>
                    <input type="text" value={cat.name} onChange={(e) => handleArrayContentChange('featuredCategories', idx, 'name', e.target.value)} className={inputClass} />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-slate-400 block mb-1">Imagen URL</label>
                    <input type="text" value={cat.img} onChange={(e) => handleArrayContentChange('featuredCategories', idx, 'img', e.target.value)} className={inputClass} />
                  </div>
                  <div>
                    <img src={cat.img} className="w-full h-24 object-cover rounded mt-2 border border-slate-200" alt="Preview" />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Beneficios Editor */}
          <div className="bg-white p-8 rounded-xl shadow-md border border-slate-200">
            <h2 className="text-xl font-bold mb-6 flex items-center underline decoration-orange-500 decoration-2 underline-offset-4">
              ⭐ Beneficios (Por qué elegirnos)
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {siteContent.benefits.map((benefit, idx) => (
                <div key={idx} className="p-4 border rounded-lg bg-slate-50 space-y-3">
                  <h4 className="font-bold text-sm text-slate-500">Beneficio {idx + 1}</h4>
                  <div className="flex items-center space-x-2 bg-white p-2 rounded mb-2">
                    <div className="text-orange-600">
                      {benefit.icon === 'Check' && <Check size={20} />}
                      {benefit.icon === 'Search' && <Search size={20} />}
                      {benefit.icon === 'ShoppingCart' && <ShoppingCart size={20} />}
                    </div>
                    <span className="text-xs font-bold text-slate-600">{benefit.icon}</span>
                  </div>
                  <div>
                    <label className="text-xs font-bold text-slate-400 block mb-1">Título</label>
                    <input type="text" value={benefit.title} onChange={(e) => handleArrayContentChange('benefits', idx, 'title', e.target.value)} className={inputClass} />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-slate-400 block mb-1">Descripción</label>
                    <textarea rows={2} value={benefit.description} onChange={(e) => handleArrayContentChange('benefits', idx, 'description', e.target.value)} className={inputClass} />
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-blue-50 text-blue-800 p-4 rounded text-sm mt-4">
            ℹ️ Los cambios se guardan automáticamente en tiempo real.
          </div>
        </div>
      )}

      {/* CONTACT TAB */}
      {activeTab === 'contact' && (
        <div className="max-w-2xl mx-auto bg-white p-8 rounded-xl shadow-md border border-slate-200">
          <h2 className="text-xl font-bold mb-6">Editar Información de Contacto</h2>
          <div className="space-y-8">
            {/* Section 1 */}
            <div className="bg-white border border-slate-200 p-4 rounded-lg shadow-sm">
              <h3 className="font-bold text-slate-800 mb-4 flex items-center"><MapPin className="mr-2" size={18} /> Sección Ubicación</h3>
              <div className="space-y-4">
                 <div>
                  <label className="block text-xs font-bold text-slate-500 mb-1 uppercase">Título de la Tarjeta</label>
                  <input type="text" name="locationTitle" value={contactInfo.locationTitle} onChange={handleContactChange} className={inputClass} />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-500 mb-1 uppercase">Dirección Física</label>
                  <input type="text" name="address" value={contactInfo.address} onChange={handleContactChange} className={inputClass} />
                </div>
              </div>
            </div>

            {/* Section 2 */}
            <div className="bg-white border border-slate-200 p-4 rounded-lg shadow-sm">
              <h3 className="font-bold text-slate-800 mb-4 flex items-center">🕒 Sección Horarios</h3>
              <div className="space-y-4">
                <div>
                  <label className="block text-xs font-bold text-slate-500 mb-1 uppercase">Título de la Tarjeta</label>
                  <input type="text" name="hoursTitle" value={contactInfo.hoursTitle} onChange={handleContactChange} className={inputClass} />
                </div>
                <div className="grid grid-cols-2 gap-4">
                   <div>
                    <label className="block text-xs font-bold text-slate-500 mb-1 uppercase">Lunes a Viernes</label>
                    <input type="text" name="hoursWeek" value={contactInfo.hoursWeek} onChange={handleContactChange} className={inputClass} />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 mb-1 uppercase">Fines de Semana</label>
                    <input type="text" name="hoursSat" value={contactInfo.hoursSat} onChange={handleContactChange} className={inputClass} />
                  </div>
                </div>
              </div>
            </div>

            {/* Section 3 */}
            <div className="bg-white border border-slate-200 p-4 rounded-lg shadow-sm">
               <h3 className="font-bold text-slate-800 mb-4 flex items-center"><Phone className="mr-2" size={18} /> Sección Contacto</h3>
               <div className="space-y-4">
                 <div>
                  <label className="block text-xs font-bold text-slate-500 mb-1 uppercase">Título de la Tarjeta</label>
                  <input type="text" name="contactTitle" value={contactInfo.contactTitle} onChange={handleContactChange} className={inputClass} />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-bold text-slate-500 mb-1 uppercase">Teléfono</label>
                    <input type="text" name="phone" value={contactInfo.phone} onChange={handleContactChange} className={inputClass} />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 mb-1 uppercase">Email</label>
                    <input type="text" name="email" value={contactInfo.email} onChange={handleContactChange} className={inputClass} />
                  </div>
                </div>
               </div>
            </div>

            <div className="bg-blue-50 text-blue-800 p-4 rounded text-sm mt-4">
              ℹ️ Los cambios en los títulos y contenidos se reflejarán instantáneamente en la página de Contacto.
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const AboutPage = ({ content }: { content: SiteContent }) => (
  <div className="container mx-auto px-4 py-16">
    <div className="max-w-3xl mx-auto text-center mb-16">
      <h1 className="text-4xl font-bold mb-6">{content.aboutTitle}</h1>
      <p className="text-xl text-slate-600 leading-relaxed whitespace-pre-line">
        {content.aboutText}
      </p>
    </div>
    
    <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center mb-20">
      <img src={content.aboutImage} alt="Workshop" className="rounded-xl shadow-xl w-full h-[400px] object-cover" />
      <div>
        <h2 className="text-2xl font-bold mb-4">{content.aboutSectionTitle}</h2>
        <p className="text-slate-600 mb-4 whitespace-pre-line leading-relaxed">
          {content.aboutSectionText}
        </p>
      </div>
    </div>

    {/* WorkShop Section */}
    <div className="bg-orange-50 rounded-3xl p-8 md:p-12 mt-12 flex flex-col md:flex-row items-start md:items-center gap-8 shadow-sm">
      <div className="bg-orange-100 p-4 rounded-full text-orange-600 flex-shrink-0">
         <Wrench size={48} />
      </div>
      <div className="flex-1">
        <h2 className="text-3xl font-bold mb-4 text-slate-900">{content.workshopTitle}</h2>
        <p className="text-lg text-slate-700 whitespace-pre-line leading-relaxed">
          {content.workshopText}
        </p>
      </div>
    </div>
  </div>
);

const ContactPage = ({ contactInfo }: { contactInfo: ContactInfo }) => (
  <div className="bg-slate-50 min-h-screen py-12">
    <div className="container mx-auto px-4">
      <div className="text-center mb-12">
        <h1 className="text-3xl font-bold mb-2">Contáctanos</h1>
        <p className="text-slate-500">Estamos aquí para ayudarte a seguir pedaleando.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
        <div className="bg-white p-8 rounded-xl shadow-md">
          <h2 className="text-xl font-bold mb-6">Envíanos un mensaje</h2>
          <form className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Nombre</label>
              <input type="text" className="w-full border border-slate-300 rounded-md p-2 focus:ring-orange-500 focus:border-orange-500" />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Email</label>
              <input type="email" className="w-full border border-slate-300 rounded-md p-2 focus:ring-orange-500 focus:border-orange-500" />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Mensaje</label>
              <textarea rows={4} className="w-full border border-slate-300 rounded-md p-2 focus:ring-orange-500 focus:border-orange-500"></textarea>
            </div>
            <Button className="w-full">Enviar Mensaje</Button>
          </form>
        </div>

        <div className="space-y-6">
           <div className="bg-white p-6 rounded-xl shadow-md flex items-start">
             <MapPin className="text-orange-600 mt-1 mr-4 flex-shrink-0" />
             <div>
               <h3 className="font-bold text-slate-900">{contactInfo.locationTitle}</h3>
               <p className="text-slate-600">{contactInfo.address}</p>
             </div>
           </div>
           
           <div className="bg-white p-6 rounded-xl shadow-md flex items-start">
             <div className="text-orange-600 mt-1 mr-4 flex-shrink-0 font-bold text-xl">🕒</div>
             <div>
               <h3 className="font-bold text-slate-900">{contactInfo.hoursTitle}</h3>
               <p className="text-slate-600">{contactInfo.hoursWeek}</p>
               <p className="text-slate-600">{contactInfo.hoursSat}</p>
             </div>
           </div>

           <div className="bg-white p-6 rounded-xl shadow-md flex items-start">
             <Phone className="text-orange-600 mt-1 mr-4 flex-shrink-0" />
             <div>
               <h3 className="font-bold text-slate-900">{contactInfo.contactTitle}</h3>
               <p className="text-slate-600">{contactInfo.phone}</p>
               <p className="text-sm text-slate-400 mt-1">{contactInfo.email}</p>
             </div>
           </div>
        </div>
      </div>
    </div>
  </div>
);

const BlogPage = ({ posts }: { posts: BlogPost[] }) => (
  <div className="container mx-auto px-4 py-16">
    <h1 className="text-3xl font-bold mb-12 text-center">Blog del Ciclista</h1>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
      {posts.map(post => (
        <article key={post.id} className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-xl transition">
          <img src={post.image} alt={post.title} className="w-full h-48 object-cover" />
          <div className="p-6">
            <div className="flex items-center justify-between text-xs text-slate-500 mb-3">
              <span>{post.date}</span>
              <span className="bg-slate-100 px-2 py-1 rounded text-orange-600 font-medium">{post.category}</span>
            </div>
            <h2 className="text-xl font-bold mb-3 hover:text-orange-600 cursor-pointer">{post.title}</h2>
            <p className="text-slate-600 text-sm mb-4">{post.excerpt}</p>
            <button className="text-orange-600 font-semibold text-sm hover:underline">Leer más &rarr;</button>
          </div>
        </article>
      ))}
    </div>
  </div>
);

const CartSidebar = ({ 
  isOpen, 
  onClose, 
  items, 
  updateQuantity,
  removeItem,
  onCheckout
}: { 
  isOpen: boolean, 
  onClose: () => void, 
  items: CartItem[],
  updateQuantity: (id: string, delta: number) => void,
  removeItem: (id: string) => void,
  onCheckout: () => void
}) => {
  const navigate = useNavigate();
  const total = items.reduce((acc, item) => acc + (item.price * item.quantity), 0);

  return (
    <div className={`fixed inset-0 z-50 transform ${isOpen ? 'translate-x-0' : 'translate-x-full'} transition-transform duration-300 ease-in-out`}>
      <div className="absolute inset-0 bg-black/50" onClick={onClose} />
      <div className="absolute right-0 top-0 h-full w-full max-w-md bg-white shadow-xl flex flex-col">
        <div className="p-4 border-b border-slate-100 flex justify-between items-center">
          <h2 className="text-lg font-bold">Carrito de Compras</h2>
          <button onClick={onClose}><X /></button>
        </div>
        
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {items.length === 0 ? (
            <div className="text-center py-20 text-slate-500 flex flex-col items-center">
              <ShoppingCart size={48} className="mx-auto mb-4 opacity-20" />
              <p className="mb-4">Tu carrito está vacío.</p>
              <Button variant="outline" size="sm" onClick={() => { onClose(); navigate('/shop'); }}>
                Ir a la Tienda
              </Button>
            </div>
          ) : (
            items.map(item => (
              <div key={item.id} className="flex gap-4 border-b border-slate-50 pb-4">
                <img src={item.image} alt={item.name} className="w-20 h-20 object-cover rounded-md" />
                <div className="flex-1">
                  <h4 className="font-semibold text-sm mb-1">{item.name}</h4>
                  <p className="text-slate-500 text-sm mb-2">${item.price.toLocaleString()}</p>
                  <div className="flex items-center gap-3">
                    <button 
                      onClick={() => updateQuantity(item.id, -1)}
                      className="w-6 h-6 rounded-full bg-slate-100 flex items-center justify-center hover:bg-slate-200"
                    >-</button>
                    <span className="text-sm w-4 text-center">{item.quantity}</span>
                    <button 
                      onClick={() => updateQuantity(item.id, 1)}
                      className="w-6 h-6 rounded-full bg-slate-100 flex items-center justify-center hover:bg-slate-200"
                    >+</button>
                    <button 
                      onClick={() => removeItem(item.id)}
                      className="ml-auto text-red-500 text-xs hover:underline"
                    >Eliminar</button>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>

        {items.length > 0 && (
           <div className="p-4 border-t border-slate-100 bg-slate-50">
             <div className="flex justify-between mb-4 font-bold text-lg">
               <span>Total:</span>
               <span>${total.toLocaleString()}</span>
             </div>
             <Button className="w-full" onClick={onCheckout}>Proceder al Pago 🔒</Button>
           </div>
        )}
      </div>
    </div>
  );
};


// --- Payment Status Component ---

const PaymentStatus = ({ status }: { status: 'success' | 'failure' | 'pending' }) => {
  const navigate = useNavigate();
  return (
    <div className="container mx-auto px-4 py-20 text-center">
      <div className={`w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6 ${
        status === 'success' ? 'bg-green-100 text-green-600' : 
        status === 'failure' ? 'bg-red-100 text-red-600' : 'bg-yellow-100 text-yellow-600'
      }`}>
        {status === 'success' ? <Check size={40} /> : status === 'failure' ? <X size={40} /> : <Search size={40} />}
      </div>
      <h1 className="text-3xl font-bold mb-4">
        {status === 'success' ? '¡Pago Exitoso!' : status === 'failure' ? 'Pago Fallido' : 'Pago Pendiente'}
      </h1>
      <p className="text-slate-600 mb-8 max-w-md mx-auto">
        {status === 'success' ? 'Gracias por tu compra. Te enviaremos un email con el detalle de tu pedido.' : 
         status === 'failure' ? 'Lo sentimos, hubo un problema al procesar tu pago. Por favor intenta de nuevo.' : 
         'Estamos procesando tu pago. Te avisaremos cuando se confirme.'}
      </p>
      <Button onClick={() => navigate('/shop')}>Volver a la Tienda</Button>
    </div>
  );
};

// --- Main App Component ---

export default function App() {
  const [products, setProducts] = useState<Product[]>([]);
  const [blogPosts, setBlogPosts] = useState<BlogPost[]>([]);
  const [cartItems, setCartItems] = useState<CartItem[]>([]);
  const [isCartOpen, setIsCartOpen] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  // Dynamic Content State
  const [siteContent, setSiteContent] = useState<SiteContent>({
    heroTitle: "Desata tu Potencial \n Sobre Ruedas",
    heroSubtitle: "Desde bicicletas de montaña de alto rendimiento hasta el repuesto más pequeño. En JorgeMotos tenemos todo lo que necesitas para tu próxima aventura.",
    heroVideo: "https://player.vimeo.com/external/434045526.sd.mp4?s=c27cf34190701814e5ad08d0d939c0fa3fd50af9&profile_id=164&oauth2_token_id=57447761",
    aboutTitle: "Sobre JorgeMotos",
    aboutText: "Más que una tienda, somos una comunidad. Nacimos en 2010 con un objetivo claro: democratizar el ciclismo de calidad y mantener cada bicicleta rodando en perfectas condiciones.",
    aboutImage: "https://images.unsplash.com/photo-1558522765-b73f8a6142c6?auto=format&fit=crop&q=80&w=800",
    aboutSectionTitle: "Nuestra Pasión",
    aboutSectionText: "Cada miembro de nuestro equipo es un ciclista activo. Entendemos lo que significa estar a mitad de una ruta y necesitar confianza absoluta en tu equipo.\n\nNos especializamos no solo en la venta, sino en el conocimiento técnico. Ya sea que busques rasurar segundos en tu crono o simplemente llegar seguro al trabajo, hablamos tu idioma.",
    workshopTitle: "Taller Mecánico Certificado",
    workshopText: "Mantenimiento preventivo, ajuste de cambios, purgado de frenos y reparaciones complejas. \n\nNuestro taller cuenta con las mejores herramientas y técnicos certificados para garantizar que tu bicicleta quede como nueva.",
    featuredCategories: [
      { name: "Montaña", img: "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?auto=format&fit=crop&q=80&w=800", cat: Category.BIKES_MOUNTAIN },
      { name: "Ruta", img: "https://images.unsplash.com/photo-1534149679361-55c328cb009c?auto=format&fit=crop&q=80&w=800", cat: Category.BIKES_ROAD },
      { name: "Accesorios", img: "https://images.unsplash.com/photo-1559056961-1f4dbbf9d36a?auto=format&fit=crop&q=80&w=800", cat: Category.ACCESSORIES }
    ],
    benefits: [
      { title: "Calidad Garantizada", description: "Trabajamos solo con marcas líderes y repuestos originales.", icon: 'Check' },
      { title: "Asesoramiento Experto", description: "¿Dudas? Nuestro equipo de mecánicos e IA están para ayudarte.", icon: 'Search' },
      { title: "Envío Rápido", description: "Envíos a todo el país en 24/48 horas para que no pares de rodar.", icon: 'ShoppingCart' }
    ]
  });

  const [contactInfo, setContactInfo] = useState<ContactInfo>({
    address: "Av. Principal 123, Ciudad",
    phone: "+123 456 7890",
    email: "contacto@jorgemotos.com",
    hoursWeek: "Lunes - Viernes: 9:00 AM - 7:00 PM",
    hoursSat: "Sábados: 10:00 AM - 2:00 PM",
    locationTitle: "Ubicación",
    hoursTitle: "Horarios",
    contactTitle: "Llámanos"
  });

  // Real-time synchronization with Firebase
  useEffect(() => {
    const unsubProducts = onSnapshot(collection(db, 'products'), (snapshot) => {
      const prods = snapshot.docs.map(doc => doc.data() as Product);
      if (prods.length === 0) {
        console.log("Database empty, products will be initialized by admin");
      } else {
        setProducts(prods);
      }
    }, (error) => handleFirestoreError(error, OperationType.GET, 'products'));

    const unsubBlog = onSnapshot(collection(db, 'blogPosts'), (snapshot) => {
      const posts = snapshot.docs.map(doc => doc.data() as BlogPost);
      if (posts.length === 0) {
         console.log("Database empty, blog will be initialized by admin");
      } else {
        setBlogPosts(posts);
      }
    }, (error) => handleFirestoreError(error, OperationType.GET, 'blogPosts'));

    const unsubContent = onSnapshot(doc(db, 'config', 'siteContent'), (snapshot) => {
      if (snapshot.exists()) {
        setSiteContent(snapshot.data() as SiteContent);
      }
    }, (error) => handleFirestoreError(error, OperationType.GET, 'config/siteContent'));

    const unsubContact = onSnapshot(doc(db, 'config', 'contactInfo'), (snapshot) => {
      if (snapshot.exists()) {
        setContactInfo(snapshot.data() as ContactInfo);
      }
    }, (error) => handleFirestoreError(error, OperationType.GET, 'config/contactInfo'));

    return () => {
      unsubProducts();
      unsubBlog();
      unsubContent();
      unsubContact();
    };
  }, []);

  const addToCart = (product: Product) => {
    setCartItems(prev => {
      const existing = prev.find(item => item.id === product.id);
      if (existing) {
        return prev.map(item => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item);
      }
      return [...prev, { ...product, quantity: 1 }];
    });
    setIsCartOpen(true);
  };

  const updateQuantity = (id: string, delta: number) => {
    setCartItems(prev => prev.map(item => {
      if (item.id === id) {
        return { ...item, quantity: Math.max(1, item.quantity + delta) };
      }
      return item;
    }));
  };

  const removeItem = (id: string) => {
    setCartItems(prev => prev.filter(item => item.id !== id));
  };

  const handleCheckout = () => {
    if (cartItems.length === 0) return;
    
    // Abrimos el link en una pestaña nueva para evitar que Mercado Pago bloquee la conexión dentro del iframe
    window.open("https://link.mercadopago.com.ar/rodadoslibertador", "_blank");
  };

  const totalItems = useMemo(() => cartItems.reduce((acc, item) => acc + item.quantity, 0), [cartItems]);

  return (
    <HashRouter>
      <div className="flex flex-col min-h-screen">
        <Header 
          cartCount={totalItems} 
          toggleCart={() => setIsCartOpen(!isCartOpen)} 
          toggleMobileMenu={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
          isMobileMenuOpen={isMobileMenuOpen}
        />
        
        <main className="flex-grow">
          <Routes>
            <Route path="/" element={<HomePage content={siteContent} />} />
            <Route path="/shop" element={<ShopPage addToCart={addToCart} products={products} />} />
            <Route path="/about" element={<AboutPage content={siteContent} />} />
            <Route path="/contact" element={<ContactPage contactInfo={contactInfo} />} />
            <Route path="/blog" element={<BlogPage posts={blogPosts} />} />
            <Route path="/success" element={<PaymentStatus status="success" />} />
            <Route path="/failure" element={<PaymentStatus status="failure" />} />
            <Route path="/pending" element={<PaymentStatus status="pending" />} />
            <Route path="/admin" element={
              <AdminPage 
                products={products} 
                siteContent={siteContent}
                contactInfo={contactInfo}
                blogPosts={blogPosts}
              />
            } />
          </Routes>
        </main>

        <Footer contactInfo={contactInfo} />

        <CartSidebar 
          isOpen={isCartOpen} 
          onClose={() => setIsCartOpen(false)} 
          items={cartItems} 
          updateQuantity={updateQuantity}
          removeItem={removeItem}
          onCheckout={handleCheckout}
        />
        
        <Chatbot />
      </div>
    </HashRouter>
  );
}